name: harpy
description: A Twitter app built with Flutter.

publish_to: 'none'

# android/version.properties is used to manage the versions
version: 0.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  android_path_provider: ^0.3.0
  built_collection: ^5.1.1
  collection: ^1.15.0
  connectivity_plus: ^2.0.2
  cupertino_icons: ^1.0.4
  dart_twitter_api: ^0.5.4
  device_info_plus: ^3.1.1
  download_manager:
    git: https://github.com/robertodoering/download_manager
  encrypt: ^5.0.1
  file_picker: ^4.0.1
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_displaymode: ^0.4.0
  flutter_feather_icons: ^2.0.0+1
  flutter_ffmpeg: ^0.4.0
  flutter_image: ^4.1.0
  flutter_keyboard_visibility: ^5.0.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10
  flutter_riverpod: ^2.0.0-dev.7
  freezed_annotation: ^2.0.3
  go_router: ^3.0.1
  google_fonts: ^2.1.0
  http: ^0.13.3
  humanizer: ^2.0.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  location: # TODO: change to pub version once updated
    git:
      url: https://github.com/TabooSun/flutterlocation.git
      path: packages/location
      ref: flutter-3-compatibility
  logging: ^1.0.1
  mime_type: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  package_info_plus: ^1.3.0
  path_provider: ^2.0.3
  permission_handler: ^9.2.0
  photo_view:
    # photo_view fork with better gesture recognition
    git: https://github.com/robertodoering/photo_view.git
  scroll_to_index: ^2.0.0
  sentry_flutter: ^6.0.0
  share_plus: ^4.0.4
  shared_preferences: ^2.0.7
  shimmer: ^2.0.0
  sliver_tools: ^0.2.6
  smooth_page_indicator: ^1.0.0+2
  timeago: ^3.0.2
  tuple: ^2.0.0
  twitter_webview_auth: ^0.1.0
  url_launcher: ^6.0.10
  uuid: ^3.0.5
  video_player: ^2.1.15
  visibility_detector: ^0.3.3
  wakelock: ^0.6.0
  waterfall_flow: ^3.0.1
  webview_flutter: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  golden_toolkit:
    # golden_toolkit fork to allow for asynchronous device wrappers
    git:
      url: https://github.com/robertodoering/flutter_glove_box
      path: packages/golden_toolkit/
  json_serializable: ^6.0.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/flare/
    - assets/changelogs/free/
    - assets/changelogs/pro/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: NotoSans
      # used as a fallback font
      # covers a lot of scripts and obscure unicode characters
      # https://fonts.google.com/specimen/Noto+Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
