name: harpy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter_twitter_login:
    git: git://github.com/eudangeld/flutter_twitter_login.git
  flutter_flux: ^4.1.2
  oauth1: ^1.0.1
  json_annotation: ^2.0.0
  path_provider: ^0.4.1
  logging: ^0.11.3+2
  intl: ^0.15.7
  cached_network_image: ^0.5.0+1
  url_launcher: ^4.0.1
  video_player: ^0.7.2
  photo_view:
    git: https://github.com/robertodoering/photo_view.git

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  mockito: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - app_config.yaml
    - example_tweet.json
  fonts:
  - family: Comfortaa
    fonts:
    - asset: assets/fonts/Comfortaa-Light.ttf
      weight: 300
    - asset: assets/fonts/Comfortaa-Regular.ttf
    - asset: assets/fonts/Comfortaa-Bold.ttf
      weight: 700

  - family: OpenSans
    fonts:
    - asset: assets/fonts/OpenSans-Light.ttf
      weight: 300
    - asset: assets/fonts/OpenSans-Regular.ttf
    - asset: assets/fonts/OpenSans-Bold.ttf
      weight: 700
