name: harpy
description: A Twitter app built with Flutter.

publish_to: 'none'

# android/version.properties is used to manage the versions
version: 0.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  android_path_provider: ^0.3.0
  any_link_preview: ^2.0.9
  built_collection: ^5.1.1
  collection: ^1.15.0
  connectivity_plus: ^2.0.2
  cupertino_icons: ^1.0.4
  dart_twitter_api: ^0.5.4
  device_info_plus: ^8.0.0
  download_manager:
    git: https://github.com/robertodoering/download_manager
  dynamic_color: ^1.4.0
  encrypt: ^5.0.1
  file_picker: ^5.0.0
  flare_flutter :
    git:
      url: https://github.com/mdpe-ir/Flare-Flutter
      path: flare_flutter
      ref: stable
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_displaymode: ^0.4.0
  flutter_feather_icons: ^2.0.0+1
  flutter_ffmpeg: ^0.4.0
  flutter_image: ^4.1.0
  flutter_keyboard_visibility: ^5.0.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10
  flutter_riverpod: ^2.0.0
  freezed_annotation: ^2.1.0
  go_router: ^4.0.0 # TODO: update once redirecting with deeplink is fixed
  google_fonts: ^3.0.0
  http: ^0.13.3
  humanizer: ^2.0.0
  intl: ^0.17.0
  json_annotation: ^4.5.0
  location: ^4.4.0
  logging: ^1.0.1
  material_color_utilities: ^0.1.5
  mime_type: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  package_info_plus: ^2.0.0
  path_provider: ^2.0.3
  permission_handler: ^10.0.0
  photo_view:
    # photo_view fork with better gesture recognition
    git: https://github.com/robertodoering/photo_view.git
  rby:
    git:
      url: https://github.com/robertodoering/rby.dart
  scroll_to_index: ^3.0.0
  sentry_flutter: ^6.9.1
  share_plus: ^5.0.0
  shared_preferences: ^2.0.7
  shimmer: ^2.0.0
  sliver_tools: ^0.2.6
  smooth_page_indicator: ^1.0.0+2
  super_sliver_list:
    git: 
      url: https://github.com/superlistapp/super_sliver_list
      ref: 2195a329cc6aacb2312038cd3fc24568ab1559d8
  timeago: ^3.0.2
  tuple: ^2.0.0
  twitter_webview_auth: ^0.1.1
  url_launcher: ^6.0.10
  uuid: ^3.0.5
  video_player: ^2.1.15
  visibility_detector: ^0.3.3
  wakelock: ^0.6.0
  waterfall_flow: ^3.0.1
  webview_flutter: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  golden_toolkit:
    # golden_toolkit fork to allow for asynchronous device wrappers
    git:
      url: https://github.com/robertodoering/flutter_glove_box
      path: packages/golden_toolkit/
  json_serializable: ^6.0.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/flare/
    - assets/changelogs/free/
    - assets/changelogs/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: NotoSans
      # used as a fallback font
      # covers a lot of scripts and obscure unicode characters
      # https://fonts.google.com/specimen/Noto+Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
